<?php
require_once 'bd.php';

/**
 * Invoice Lines Model.
 *
 * Represents the 'lineas_facturas' table in the database.
 * Handles CRUD operations for invoice items.
 */
class LineasFacturasModelo extends BD
{
    /**
     * @var int Line ID.
     */
    public $id;

    /**
     * @var int Invoice ID this line belongs to.
     */
    public $factura_id;

    /**
     * @var string Item/Product Reference.
     */
    public $referencia;

    /**
     * @var string Item Description.
     */
    public $descripcion;

    /**
     * @var float Quantity.
     */
    public $cantidad;

    /**
     * @var float Unit Price.
     */
    public $precio;

    /**
     * @var float VAT Rate/Amount.
     */
    public $iva;

    /**
     * @var float Line Total Amount (generated by DB or trigger).
     */
    public $importe;

    /**
     * @var array|null Array of selected records (objects).
     */
    public $filas = null;

    /**
     * Insert a new invoice line.
     *
     * Inserts the current object properties into the database.
     * Note: 'importe' is skipped as it is calculated by the database.
     *
     * @return int|false The number of affected rows (1 on success), or false on error.
     */
    public function Insertar()
    {
        // Insert new line; 'importe' field is generated by DB and not passed
        $sql = "INSERT INTO lineas_facturas (factura_id, referencia, descripcion, cantidad, precio, iva) VALUES
                ('$this->factura_id',
                '$this->referencia',
                '$this->descripcion',
                '$this->cantidad',
                '$this->precio',
                '$this->iva')";

        return $this->_ejecutar($sql);
    }

    /**
     * Update an existing invoice line.
     *
     * Updates the database record matching the current ID with new property values.
     *
     * @return int|false The number of affected rows, or false on error.
     */
    public function Modificar()
    {
        $sql = "UPDATE lineas_facturas SET
                factura_id='$this->factura_id',
                referencia='$this->referencia',
                descripcion='$this->descripcion',
                cantidad='$this->cantidad',
                precio='$this->precio',
                iva='$this->iva'
                WHERE id=$this->id";

        return $this->_ejecutar($sql);
    }

    /**
     * Delete an invoice line.
     *
     * Deletes the record matching the current ID from the database.
     *
     * @return int|false The number of affected rows, or false on error.
     */
    public function Borrar()
    {
        $sql = "DELETE FROM lineas_facturas WHERE id=$this->id";
        return $this->_ejecutar($sql);
    }

    /**
     * Select invoice lines.
     *
     * Retrieves records from the database. Can filter by ID or by Invoice ID.
     * If a specific ID is set, populates the object properties with the result.
     *
     * @return bool True if records were found, false otherwise.
     */
    public function Seleccionar()
    {
        $sql = 'SELECT * FROM lineas_facturas';

        // If ID is set, filter by it
        if ($this->id != 0) {
            $sql .= " WHERE id=$this->id";
        }
        // Otherwise, if factura_id is set, filter by invoice
        else if ($this->factura_id != 0) {
            $sql .= " WHERE factura_id=$this->factura_id";
        }

        $this->filas = $this->_consultar($sql);

        if ($this->filas == null) {
            return false;
        }

        // If a single record was selected by ID, fill object properties
        if ($this->id != 0) {
            $this->factura_id = $this->filas[0]->factura_id;
            $this->referencia = $this->filas[0]->referencia;
            $this->descripcion = $this->filas[0]->descripcion;
            $this->cantidad = $this->filas[0]->cantidad;
            $this->precio = $this->filas[0]->precio;
            $this->iva = $this->filas[0]->iva;
            $this->importe = $this->filas[0]->importe;
        }

        return true;
    }
}
